/**
 * Somatus Patient Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.7.0-23-03-09-18-54
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CodeAndLabel } from '../model/codeAndLabel';
import { RecipeDetails } from '../model/recipeDetails';
import { RecipeInfo } from '../model/recipeInfo';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CookbookService {

    protected basePath = 'https://web-patient-dev-api.azurewebsites.net/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param recipeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cookbookAddFavorite(recipeId: string, observe?: 'body', reportProgress?: boolean): Observable<RecipeDetails>;
    public cookbookAddFavorite(recipeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecipeDetails>>;
    public cookbookAddFavorite(recipeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecipeDetails>>;
    public cookbookAddFavorite(recipeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling cookbookAddFavorite.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RecipeDetails>('put',`${this.basePath}/api/Cookbook/${encodeURIComponent(String(recipeId))}/favorite`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cookbookGetCategories(observe?: 'body', reportProgress?: boolean): Observable<Array<CodeAndLabel>>;
    public cookbookGetCategories(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CodeAndLabel>>>;
    public cookbookGetCategories(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CodeAndLabel>>>;
    public cookbookGetCategories(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CodeAndLabel>>('get',`${this.basePath}/api/Cookbook/categories`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param recipeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cookbookGetRecipeDetails(recipeId: string, observe?: 'body', reportProgress?: boolean): Observable<RecipeDetails>;
    public cookbookGetRecipeDetails(recipeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecipeDetails>>;
    public cookbookGetRecipeDetails(recipeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecipeDetails>>;
    public cookbookGetRecipeDetails(recipeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling cookbookGetRecipeDetails.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RecipeDetails>('get',`${this.basePath}/api/Cookbook/${encodeURIComponent(String(recipeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cookbookGetRecipes(observe?: 'body', reportProgress?: boolean): Observable<Array<RecipeInfo>>;
    public cookbookGetRecipes(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RecipeInfo>>>;
    public cookbookGetRecipes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RecipeInfo>>>;
    public cookbookGetRecipes(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<RecipeInfo>>('get',`${this.basePath}/api/Cookbook`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param recipeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cookbookRemoveFavorite(recipeId: string, observe?: 'body', reportProgress?: boolean): Observable<RecipeDetails>;
    public cookbookRemoveFavorite(recipeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecipeDetails>>;
    public cookbookRemoveFavorite(recipeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecipeDetails>>;
    public cookbookRemoveFavorite(recipeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling cookbookRemoveFavorite.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<RecipeDetails>('delete',`${this.basePath}/api/Cookbook/${encodeURIComponent(String(recipeId))}/favorite`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
