/**
 * Somatus Patient Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.7.0-23-03-09-18-54
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AuthToken } from '../model/authToken';
import { CareMemberLearningCategoryContent } from '../model/careMemberLearningCategoryContent';
import { InvitePatientRequest2 } from '../model/invitePatientRequest2';
import { InvitePatientResponse } from '../model/invitePatientResponse';
import { PatientAccountInfo } from '../model/patientAccountInfo';
import { PatientStatus } from '../model/patientStatus';
import { RcLoginRequest } from '../model/rcLoginRequest';
import { UpdateLearningCenterRecommendationRequest } from '../model/updateLearningCenterRecommendationRequest';
import { UpdateLearningCenterRecommendationResponse } from '../model/updateLearningCenterRecommendationResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RcAccessService {

    protected basePath = 'https://web-patient-dev-api.azurewebsites.net/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param memberId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessGetPatientAccountInfo(memberId: string, observe?: 'body', reportProgress?: boolean): Observable<PatientAccountInfo>;
    public rcAccessGetPatientAccountInfo(memberId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PatientAccountInfo>>;
    public rcAccessGetPatientAccountInfo(memberId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PatientAccountInfo>>;
    public rcAccessGetPatientAccountInfo(memberId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling rcAccessGetPatientAccountInfo.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PatientAccountInfo>('get',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(memberId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param data 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessGetPatientStatus(data?: string, observe?: 'body', reportProgress?: boolean): Observable<PatientStatus>;
    public rcAccessGetPatientStatus(data?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PatientStatus>>;
    public rcAccessGetPatientStatus(data?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PatientStatus>>;
    public rcAccessGetPatientStatus(data?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (data !== undefined && data !== null) {
            queryParameters = queryParameters.set('data', <any>data);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PatientStatus>('get',`${this.basePath}/api/RcAccess/patient/status`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param memberId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessInvitePatient(body: InvitePatientRequest2, memberId: string, observe?: 'body', reportProgress?: boolean): Observable<InvitePatientResponse>;
    public rcAccessInvitePatient(body: InvitePatientRequest2, memberId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvitePatientResponse>>;
    public rcAccessInvitePatient(body: InvitePatientRequest2, memberId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvitePatientResponse>>;
    public rcAccessInvitePatient(body: InvitePatientRequest2, memberId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rcAccessInvitePatient.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling rcAccessInvitePatient.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<InvitePatientResponse>('post',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(memberId))}/invite`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessLearningCenter(observe?: 'body', reportProgress?: boolean): Observable<Array<CareMemberLearningCategoryContent>>;
    public rcAccessLearningCenter(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CareMemberLearningCategoryContent>>>;
    public rcAccessLearningCenter(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CareMemberLearningCategoryContent>>>;
    public rcAccessLearningCenter(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CareMemberLearningCategoryContent>>('get',`${this.basePath}/api/RcAccess/patient/learning-center`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessLogin(body: RcLoginRequest, observe?: 'body', reportProgress?: boolean): Observable<AuthToken>;
    public rcAccessLogin(body: RcLoginRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthToken>>;
    public rcAccessLogin(body: RcLoginRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthToken>>;
    public rcAccessLogin(body: RcLoginRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rcAccessLogin.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<AuthToken>('post',`${this.basePath}/api/RcAccess/login`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param userId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessResetPassword(userId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public rcAccessResetPassword(userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public rcAccessResetPassword(userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public rcAccessResetPassword(userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling rcAccessResetPassword.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('put',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(userId))}/reset-password`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param userId 
     * @param mode 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessSendHomeLink(userId: string, mode?: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public rcAccessSendHomeLink(userId: string, mode?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public rcAccessSendHomeLink(userId: string, mode?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public rcAccessSendHomeLink(userId: string, mode?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling rcAccessSendHomeLink.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (mode !== undefined && mode !== null) {
            queryParameters = queryParameters.set('mode', <any>mode);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('put',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(userId))}/send-home-link`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param userId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessUpdateLearningCenterRecommendations(body: UpdateLearningCenterRecommendationRequest, userId: string, observe?: 'body', reportProgress?: boolean): Observable<UpdateLearningCenterRecommendationResponse>;
    public rcAccessUpdateLearningCenterRecommendations(body: UpdateLearningCenterRecommendationRequest, userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UpdateLearningCenterRecommendationResponse>>;
    public rcAccessUpdateLearningCenterRecommendations(body: UpdateLearningCenterRecommendationRequest, userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UpdateLearningCenterRecommendationResponse>>;
    public rcAccessUpdateLearningCenterRecommendations(body: UpdateLearningCenterRecommendationRequest, userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rcAccessUpdateLearningCenterRecommendations.');
        }

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling rcAccessUpdateLearningCenterRecommendations.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UpdateLearningCenterRecommendationResponse>('post',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(userId))}/learning-center/recommendations`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param memberId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessUpdatePreRecommendations(body: UpdateLearningCenterRecommendationRequest, memberId: string, observe?: 'body', reportProgress?: boolean): Observable<InvitePatientResponse>;
    public rcAccessUpdatePreRecommendations(body: UpdateLearningCenterRecommendationRequest, memberId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvitePatientResponse>>;
    public rcAccessUpdatePreRecommendations(body: UpdateLearningCenterRecommendationRequest, memberId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvitePatientResponse>>;
    public rcAccessUpdatePreRecommendations(body: UpdateLearningCenterRecommendationRequest, memberId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rcAccessUpdatePreRecommendations.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling rcAccessUpdatePreRecommendations.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<InvitePatientResponse>('post',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(memberId))}/learning-center/pre-recommendations`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param userId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rcAccessUserLearningCenter(userId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CareMemberLearningCategoryContent>>;
    public rcAccessUserLearningCenter(userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CareMemberLearningCategoryContent>>>;
    public rcAccessUserLearningCenter(userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CareMemberLearningCategoryContent>>>;
    public rcAccessUserLearningCenter(userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling rcAccessUserLearningCenter.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CareMemberLearningCategoryContent>>('get',`${this.basePath}/api/RcAccess/patient/${encodeURIComponent(String(userId))}/learning-center`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
