/**
 * Somatus Patient Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.7.0-23-03-09-18-54
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TopicInfo } from './topicInfo';
import { UserInfo } from './userInfo';

export interface FullArticleInfo { 
    id?: string;
    title?: string;
    content?: string;
    imageUrl?: string;
    replyEnabled: boolean;
    active: boolean;
    published: boolean;
    publishedBy?: UserInfo;
    publishedOn?: Date;
    createdBy?: UserInfo;
    createdOn: Date;
    updatedBy?: UserInfo;
    updatedOn: Date;
    topics?: Array<TopicInfo>;
    likesCount: number;
    commentsCount: number;
    liked: boolean;
    saved: boolean;
}