/**
 * Somatus Patient Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.7.0-23-03-09-18-54
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PatientDoc { 
    patientDocId: number;
    ccaPatientId?: number;
    docTypeId?: number;
    title?: string;
    isDigitalSignRequired?: number;
    isDigitallySigned?: number;
    digitalSignedOn?: Date;
    priority?: string;
    visitedOn?: Date;
    docPath?: string;
    docType?: string;
    docMimeType?: string;
    isDownlodable?: number;
    isDeleted?: number;
    isActive?: number;
    createdOn?: Date;
    createdBy?: string;
    updatedOn?: Date;
    updatedBy?: string;
}