# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: QA
    jobs:
      - job: QAjob
    
  - stage: prod
    jobs:
      - job: prodjob

    
  - stage: test
    jobs:
      - job: testjob